#!/usr/bin/env bash
# Script that displays information about subdomains

domain_info () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1)
    record=$(echo $line | awk '{print $4}')
    destination=$(echo $line | awk '{print $5}')
    echo "The subdomain $2 is a $record record and points to $destination"
}

if [ "$#" == 1 ]; then
    domain_info "$1" "www"
    domain_info "$1" "lb-01"
    domain_info "$1" "web-01"
    domain_info "$1" "web-02"
elif [ "$#" == 2 ]; then
    domain_info "$1" "$2"
fi

